services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - RAILS_ENV=development
      - API_AUTHORIZATION=development
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ".:/e-core-teams"
  db:
    container_name: 'db'
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - "db:/var/lib/postgresql/data"
  redis:
    container_name: 'redis'
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - "redis:/data"
volumes:
  db:
  redis:

